import { z } from "zod";

export const createPropertySchema = z.object({
  title: z.string().min(1).max(200),
  images: z.array(z.string().min(1)).min(1).max(20),
  location: z.string().min(1).max(200),
  price: z.number().positive(),
  type: z.enum(["residential", "commercial", "land"]).default("residential"),
  category: z.enum(["arbitrage", "mortgage", "airbnb"]).default("arbitrage"),
  investmentType: z.enum(["individual", "pooled"]).default("individual"),
  minInvestment: z.number().positive(),
  maxInvestment: z.number().positive(),
  targetAmount: z.number().positive(),
  currentFunded: z.number().min(0).default(0),
  investorCount: z.number().int().min(0).default(0),
  expectedROI: z.number().min(0).max(100),
  monthlyReturn: z.number().min(0).max(100),
  duration: z.number().int().positive().default(12),
  bedrooms: z.number().int().min(0).default(0),
  bathrooms: z.number().int().min(0).default(0),
  parking: z.number().int().min(0).default(0),
  sqft: z.number().int().positive(),
  description: z.string().min(10).max(2000),
  features: z.array(z.string().max(100)).max(50).default([]),
  investmentStatus: z.enum(["available", "fully-funded", "coming-soon", "closed"]).default("available"),
  riskLevel: z.enum(["low", "medium", "high"]).default("low"),
  isFeatured: z.boolean().default(false),
});

export const updatePropertySchema = z.object({
  title: z.string().min(1).max(200).optional(),
  images: z.array(z.string().url()).min(1).max(20).optional(),
  location: z.string().min(1).max(200).optional(),
  price: z.number().positive().optional(),
  type: z.enum(["residential", "commercial", "land"]).optional(),
  category: z.enum(["arbitrage", "mortgage", "airbnb"]).optional(),
  investmentType: z.enum(["individual", "pooled"]).optional(),
  minInvestment: z.number().positive().optional(),
  maxInvestment: z.number().positive().optional(),
  targetAmount: z.number().positive().optional(),
  currentFunded: z.number().min(0).optional(),
  investorCount: z.number().int().min(0).optional(),
  expectedROI: z.number().min(0).max(100).optional(),
  monthlyReturn: z.number().min(0).max(100).optional(),
  duration: z.number().int().positive().optional(),
  bedrooms: z.number().int().min(0).optional(),
  bathrooms: z.number().int().min(0).optional(),
  parking: z.number().int().min(0).optional(),
  sqft: z.number().int().positive().optional(),
  description: z.string().min(10).max(2000).optional(),
  features: z.array(z.string().max(100)).max(50).optional(),
  investmentStatus: z.enum(["available", "fully-funded", "coming-soon", "closed"]).optional(),
  riskLevel: z.enum(["low", "medium", "high"]).optional(),
  isActive: z.boolean().optional(),
  isFeatured: z.boolean().optional(),
});
